"""The virtual eMMC controller.

One object owns the two things a repair session actually asks a chip for:

* its **registers** (CID / CSD / EXT_CSD, including the wear and health bytes), and
* its **user area** - a real file on disk with a real GPT and real partition content.

Both are live. The registers are generated by `extcsd_virtual` and decoded again by
`revive.storage.emmc`; the user area is read and written through ordinary file IO, which means
`revive.ops.dump.analyse` and `revive.storage.gpt` work on it exactly as they work on a dump.

Health, capacity, manufacturer and firmware version can all be changed at will, and the change
is reflected in what the real decoder reports - that is the whole point of the lab.
"""
from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

from .. import util
from ..storage import emmc as emmc_mod
from ..util import human_size, sha256_bytes
from . import extcsd_virtual as regs
from .extcsd_virtual import DEAD, HEALTHY, HEALTH_STATES, RegisterSpec, WARNING
from .partitions import SECTOR, VirtualPartition

LOG = logging.getLogger("revive.lab.emmc")

DEFAULT_IMAGE_BYTES = 32 * 1024 * 1024
MIN_IMAGE_BYTES = 4 * 1024 * 1024

# eMMC hardware partitions a technician can select. The lab models boot1/boot2 as small
# regions at the front of the user area image, which is enough to exercise region-aware code.
REGIONS = ("user", "boot1", "boot2", "rpmb")
BOOT_REGION_BYTES = 4 * 1024 * 1024
RPMB_BYTES = 128 * 1024


class VirtualEmmcError(Exception):
    """Raised when the virtual chip refuses an operation, the way a real one would."""


@dataclass
class BadBlock:
    """A block the chip can no longer serve reliably."""

    offset: int = 0
    size: int = 4096
    state: str = "unreadable"          # unreadable | unstable | rewritten

    @property
    def offset_hex(self) -> str:
        return f"0x{self.offset:x}"

    def to_dict(self) -> Dict[str, Any]:
        return {"offset": self.offset, "offset_hex": self.offset_hex, "size": self.size,
                "size_human": human_size(self.size), "state": self.state}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "BadBlock":
        return cls(offset=int(data.get("offset", 0)), size=int(data.get("size", 4096)),
                   state=str(data.get("state", "unreadable")))


@dataclass
class StorageCounters:
    """Wear counters. Real chips track these in firmware; the lab tracks them in the open."""

    reads: int = 0
    writes: int = 0
    erases: int = 0
    bytes_read: int = 0
    bytes_written: int = 0
    failed_reads: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {"reads": self.reads, "writes": self.writes, "erases": self.erases,
                "bytes_read": self.bytes_read, "bytes_written": self.bytes_written,
                "bytes_written_human": human_size(self.bytes_written),
                "failed_reads": self.failed_reads}


class VirtualEMMC:
    """A simulated eMMC chip: registers + a user area file, with wear and bad blocks."""

    def __init__(self, path, spec: Optional[RegisterSpec] = None,
                 sector_size: int = SECTOR, golden_dir=None):
        self.path = Path(path)
        self.spec = spec or RegisterSpec()
        self.sector_size = int(sector_size)
        self.golden_dir = Path(golden_dir) if golden_dir else None
        self.bad_blocks: List[BadBlock] = [BadBlock.from_dict(b)
                                           for b in self.spec.bad_blocks]
        self.counters = StorageCounters()
        self.notes: List[str] = []

    # -- construction ------------------------------------------------------------------
    @classmethod
    def create(cls, path, capacity_bytes: int = 64 * 1024 ** 3,
               image_bytes: int = DEFAULT_IMAGE_BYTES, sector_size: int = SECTOR,
               golden_dir=None, **spec_kwargs) -> "VirtualEMMC":
        """Create the image file and the registers for a new chip."""
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        image_bytes = max(MIN_IMAGE_BYTES, int(image_bytes))
        spec = RegisterSpec(capacity_bytes=int(capacity_bytes), **spec_kwargs)
        emmc = cls(target, spec=spec, sector_size=sector_size, golden_dir=golden_dir)
        emmc.recreate_image(image_bytes)
        LOG.info("created a virtual %s eMMC (%s nominal, %s image) at %s",
                 spec.manufacturer, human_size(capacity_bytes), human_size(image_bytes), target)
        return emmc

    def recreate_image(self, image_bytes: int = DEFAULT_IMAGE_BYTES) -> int:
        """(Re)create the user area file. Partition content and the GPT are written by the device."""
        image_bytes = max(MIN_IMAGE_BYTES, int(image_bytes))
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self.path.open("wb") as fh:
            # Written in blocks rather than as one sparse seek, so the file is genuinely there
            # on filesystems that do not support sparse files.
            block = b"\x00" * (1024 * 1024)
            remaining = image_bytes
            while remaining > 0:
                chunk = block[:min(len(block), remaining)]
                fh.write(chunk)
                remaining -= len(chunk)
            fh.flush()
        return image_bytes

    def resize_image(self, image_bytes: int) -> int:
        """Grow or shrink the user area file (the layout has to be rebuilt afterwards)."""
        image_bytes = max(MIN_IMAGE_BYTES, int(image_bytes))
        current = self.path.stat().st_size if self.path.exists() else 0
        if not self.path.exists():
            return self.recreate_image(image_bytes)
        with self.path.open("r+b") as fh:
            fh.truncate(image_bytes)
            if image_bytes > current:
                fh.seek(current)
                remaining = image_bytes - current
                block = b"\x00" * (1024 * 1024)
                while remaining > 0:
                    chunk = block[:min(len(block), remaining)]
                    fh.write(chunk)
                    remaining -= len(chunk)
            fh.flush()
        LOG.info("resized the virtual eMMC image %s -> %s", human_size(current),
                 human_size(image_bytes))
        return image_bytes

    @property
    def image_bytes(self) -> int:
        return self.path.stat().st_size if self.path.exists() else 0

    @property
    def sectors(self) -> int:
        return self.image_bytes // self.sector_size

    # -- registers ---------------------------------------------------------------------
    @property
    def cid(self) -> bytes:
        return regs.build_cid(self.spec)

    @property
    def csd(self) -> bytes:
        return regs.build_csd(self.spec)

    @property
    def ext_csd(self) -> bytes:
        return regs.build_ext_csd(self.spec)

    def registers(self) -> Dict[str, str]:
        """The raw registers, hex encoded - what `revive identify` prints."""
        return {"cid": self.cid.hex(), "csd": self.csd.hex(), "ext_csd": self.ext_csd.hex()}

    def registers_decoded(self) -> Dict[str, Any]:
        """Decode the registers with Revive's real parser (summary + verdict + findings)."""
        return regs.decode(self.spec)

    def ext_csd_info(self) -> emmc_mod.ExtCsdInfo:
        return emmc_mod.parse_ext_csd(self.ext_csd)

    def assess(self) -> Dict[str, Any]:
        """The eMMC health verdict, straight from `revive.storage.emmc.assess`."""
        return self.registers_decoded()["assessment"]

    def health(self) -> Dict[str, Any]:
        """Everything a technician wants to know about the chip's condition in one dict."""
        decoded = self.registers_decoded()
        estimate = regs.life_estimate(self.spec)
        return {
            "state": self.spec.state, "pre_eol": f"0x{self.spec.pre_eol_value:02X}",
            "pre_eol_text": decoded["ext_csd"]["pre_eol"],
            "life_a": estimate["life_a"], "life_b": estimate["life_b"],
            "life_a_text": estimate["life_a_text"], "life_b_text": estimate["life_b_text"],
            "used_percent_estimate": estimate["used_percent_estimate"],
            "remaining_percent_estimate": estimate["remaining_percent_estimate"],
            "write_cycles": estimate["write_cycles"],
            "cycles_left_estimate": estimate["cycles_left_estimate"],
            "bad_blocks": len(self.bad_blocks),
            "verdict": decoded["verdict"], "findings": decoded["findings"],
            "capacity_bytes": self.spec.capacity_bytes,
            "capacity_human": human_size(self.spec.capacity_bytes),
            "device_version": decoded["ext_csd"]["device_version"],
            "firmware_version": decoded["ext_csd"]["firmware_version"],
            "manufacturer": decoded["cid"]["manufacturer"],
            "product_name": decoded["cid"]["product_name"],
            "serial": decoded["cid"]["serial"],
            "warnings": decoded["ext_csd"]["warnings"],
        }

    def signals(self) -> List[str]:
        """Fault signals derivable from the registers alone."""
        out: List[str] = []
        verdict = self.assess().get("verdict", "ok")
        if self.spec.pre_eol_value >= 0x03:
            out.append("emmc_pre_eol_urgent")
        elif self.spec.pre_eol_value == 0x02:
            out.append("emmc_pre_eol_warning")
        if (self.spec.life_a_value or 0) >= 0x0B or (self.spec.life_b_value or 0) >= 0x0B:
            out.append("emmc_life_exceeded")
        if self.bad_blocks:
            out.append("emmc_bad_blocks")
        if verdict in ("warn", "fatal"):
            out.append("emmc_health_" + verdict)
        return out

    # -- register setters --------------------------------------------------------------
    def set_health(self, state: str) -> Dict[str, Any]:
        """healthy / warning / dead - the PRE_EOL and life-time bytes move together."""
        state = (state or "").lower()
        if state not in HEALTH_STATES:
            raise VirtualEmmcError(f"unknown health state {state!r}; expected one of "
                                   f"{', '.join(HEALTH_STATES)}")
        self.spec = self.spec.with_health(state)
        LOG.info("virtual eMMC health set to %s (PRE_EOL 0x%02X)", state, self.spec.pre_eol_value)
        return {"health": self.spec.state, "pre_eol": f"0x{self.spec.pre_eol_value:02X}",
                "life_a": f"0x{self.spec.life_a_value:02X}",
                "life_b": f"0x{self.spec.life_b_value:02X}",
                "verdict": self.assess().get("verdict")}

    def set_pre_eol(self, value) -> Dict[str, Any]:
        """Set PRE_EOL_INFO directly. Accepts 2, "2" or "0x02" - it is a byte, after all."""
        try:
            self.spec.pre_eol = int(str(value).strip(), 0)
        except (TypeError, ValueError) as exc:
            raise VirtualEmmcError(f"{value!r} is not a PRE_EOL_INFO byte") from exc
        return {"pre_eol": f"0x{self.spec.pre_eol_value:02X}", "state": self.spec.state}

    def set_life(self, life_a: Optional[int] = None, life_b: Optional[int] = None) -> Dict[str, Any]:
        if life_a is not None:
            self.spec.life_a = int(life_a) & 0xFF
        if life_b is not None:
            self.spec.life_b = int(life_b) & 0xFF
        return {"life_a": f"0x{self.spec.life_a_value:02X}",
                "life_b": f"0x{self.spec.life_b_value:02X}"}

    def set_manufacturer(self, name: str) -> Dict[str, Any]:
        """Change the reported maker. An unknown name is allowed but noted, like a real chip."""
        name = str(name or "").strip()
        if not name:
            raise VirtualEmmcError("a manufacturer name is required")
        known = name.lower() in {v.lower() for v in emmc_mod.MANUFACTURERS.values()}
        self.spec = self.spec.updated(manufacturer=name)
        note = None
        if not known:
            note = (f"{name} is not in Revive's manufacturer table; the chip reports "
                    f"MID 0x{_mid_hex(name)} and the name is shown as unknown")
            if note not in self.notes:
                self.notes.append(note)
        decoded = regs.decode(self.spec)["cid"]
        return {"manufacturer": decoded["manufacturer"], "mid": decoded["mid"],
                "product_name": decoded["product_name"], "note": note}

    def set_product_name(self, name: str) -> Dict[str, Any]:
        # PNM is six ASCII bytes; `updated()` clamps it the way construction does.
        self.spec = self.spec.updated(product_name=name)
        return {"product_name": regs.decode(self.spec)["cid"]["product_name"]}

    def set_firmware_version(self, version) -> Dict[str, Any]:
        """Firmware version is 8 ASCII bytes in the EXT_CSD.

        A `0x29534c42`-style value is ten characters and cannot fit, so it is normalised to the
        hex digits instead of being truncated into something the chip never reported.
        """
        self.spec = self.spec.updated(firmware_version=version)
        return {"firmware_version": regs.decode(self.spec)["ext_csd"]["firmware_version"]}

    def set_serial(self, value) -> Dict[str, Any]:
        """The CID serial number - four bytes, so it wraps like the field does."""
        try:
            serial = int(str(value).strip(), 0)
        except (TypeError, ValueError) as exc:
            raise VirtualEmmcError(f"{value!r} is not a serial number") from exc
        self.spec = self.spec.updated(serial=serial)
        return {"serial": f"0x{self.spec.serial:08X}"}

    def set_write_cycles(self, cycles: int) -> Dict[str, Any]:
        """How worn the chip is, in 4 MiB programme/erase cycles - the lifetime estimate."""
        cycles = max(0, int(cycles))
        self.spec = self.spec.updated(write_cycles=cycles)
        estimate = regs.life_estimate(self.spec)
        LOG.info("virtual eMMC wear set to %d cycle(s): %s", cycles, estimate["verdict"])
        return {"write_cycles": cycles, "verdict": estimate["verdict"],
                "cycles_left_estimate": estimate["cycles_left_estimate"]}

    def set_capacity(self, capacity_bytes: int) -> Dict[str, Any]:
        """Change the nominal capacity the registers report (SEC_COUNT, CSD)."""
        capacity_bytes = int(capacity_bytes)
        if capacity_bytes < 512 * 1024:
            raise VirtualEmmcError("a capacity below 512 KiB is not a plausible eMMC")
        self.spec.capacity_bytes = capacity_bytes
        LOG.info("virtual eMMC capacity set to %s", human_size(capacity_bytes))
        return {"capacity_bytes": capacity_bytes, "capacity_human": human_size(capacity_bytes),
                "sec_count": self.spec.sec_count}

    def set_size(self, text) -> Dict[str, Any]:
        """`set_size('128GB')` / `set_size('64G')` - the size a product sheet would quote."""
        return self.set_capacity(util.parse_size(str(text)))

    # -- bad blocks --------------------------------------------------------------------
    def add_bad_block(self, offset: int, size: int = 4096,
                      state: str = "unreadable") -> Dict[str, Any]:
        """Record a bad block. Enough of them and the wear flags follow, as on a real chip."""
        block = BadBlock(offset=int(offset), size=int(size), state=state)
        self.bad_blocks.append(block)
        record = regs.add_bad_block(self.spec, block.offset, block.size, block.state)
        LOG.info("bad block at %s (%d total)", block.offset_hex, len(self.bad_blocks))
        return {**block.to_dict(), "total": len(self.bad_blocks),
                "pre_eol": record and f"0x{self.spec.pre_eol_value:02X}"}

    def add_random_bad_blocks(self, count: int = 8, region_start: int = 0,
                              region_end: Optional[int] = None) -> List[Dict[str, Any]]:
        """Scatter bad blocks across the user area, the way a worn chip presents them."""
        import random

        end = region_end if region_end is not None else max(self.image_bytes, 1024 * 1024)
        span = max(0, end - region_start)
        out: List[Dict[str, Any]] = []
        for _ in range(max(0, int(count))):
            offset = region_start + (random.randrange(span) // 4096) * 4096 if span else region_start
            out.append(self.add_bad_block(offset))
        return out

    def is_bad(self, offset: int) -> Optional[BadBlock]:
        for block in self.bad_blocks:
            if block.offset <= offset < block.offset + block.size:
                return block
        return None

    # -- user area IO ------------------------------------------------------------------
    def read(self, offset: int, length: int) -> bytes:
        """Read the user area. Reads that hit a bad block fail, like they do on real silicon."""
        self._require_image()
        size = self.image_bytes
        if offset < 0 or offset >= size:
            raise VirtualEmmcError(f"read at 0x{offset:x} is outside the "
                                   f"{human_size(size)} user area")
        length = min(int(length), size - offset)
        block = self.is_bad(offset)
        if block is not None:
            self.counters.failed_reads += 1
            raise VirtualEmmcError(
                f"read failed at {block.offset_hex}: the chip reports a {block.state} block here")
        with self.path.open("rb") as fh:
            fh.seek(offset)
            data = fh.read(length)
        self.counters.reads += 1
        self.counters.bytes_read += len(data)
        return data

    def write(self, offset: int, data: bytes) -> int:
        """Write the user area. A worn chip accepts the write and then corrupts it - so do we."""
        self._require_image()
        size = self.image_bytes
        if offset < 0 or offset + len(data) > size:
            raise VirtualEmmcError(
                f"write of {human_size(len(data))} at 0x{offset:x} does not fit in the "
                f"{human_size(size)} user area")
        payload = bytearray(data)
        if self.spec.pre_eol_value >= 0x03:
            # PRE_EOL urgent: the write "succeeds" but bits do not stick. This is the failure
            # that makes a reflash look like it worked and then boot-loop.
            corrupted = 0
            for index in range(0, len(payload), 4096):
                payload[index] ^= 0xFF
                corrupted += 1
            LOG.warning("PRE_EOL is urgent: %d block(s) were written but will not hold", corrupted)
            self.notes.append("writes were accepted but PRE_EOL_INFO is urgent - the data will "
                              "not hold; this is why Revive refuses to flash a dying chip")
        with self.path.open("r+b") as fh:
            fh.seek(offset)
            fh.write(bytes(payload))
            fh.flush()
        self.counters.writes += 1
        self.counters.bytes_written += len(payload)
        self.spec.write_cycles += max(1, len(payload) // (4 * 1024 * 1024))
        return len(payload)

    def erase(self, offset: int, length: int) -> int:
        self._require_image()
        data = b"\x00" * int(length)
        with self.path.open("r+b") as fh:
            fh.seek(offset)
            fh.write(data)
            fh.flush()
        self.counters.erases += 1
        return len(data)

    # -- partition level helpers -------------------------------------------------------
    def read_partition(self, part: VirtualPartition) -> bytes:
        return self.read(part.offset, part.size)

    def write_partition(self, part: VirtualPartition, data: bytes) -> int:
        return self.write(part.offset, data[:part.size].ljust(part.size, b"\x00")
                          if len(data) < part.size else data[:part.size])

    def partition_checksum(self, part: VirtualPartition) -> str:
        """SHA-256 of the partition content, so a repair can be proven by comparison."""
        try:
            return sha256_bytes(self.read_partition(part))
        except VirtualEmmcError as exc:
            LOG.warning("cannot checksum %s: %s", part.name, exc)
            return ""

    def save_golden(self, part: VirtualPartition) -> Optional[Path]:
        """Keep a known-good copy of a partition, the way a technician backs up before flashing."""
        if not self.golden_dir:
            return None
        try:
            data = self.read_partition(part)
        except VirtualEmmcError as exc:
            LOG.warning("cannot take a golden copy of %s: %s", part.name, exc)
            return None
        self.golden_dir.mkdir(parents=True, exist_ok=True)
        target = self.golden_dir / f"{part.name}.img"
        util.atomic_write(target, data)
        return target

    def restore_golden(self, part: VirtualPartition) -> Dict[str, Any]:
        """Write the known-good copy back. Returns what was restored and its checksum."""
        if not self.golden_dir:
            raise VirtualEmmcError("this device has no golden copies to restore from")
        source = self.golden_dir / f"{part.name}.img"
        if not source.exists():
            raise VirtualEmmcError(f"no golden copy of {part.name} was taken")
        data = source.read_bytes()
        written = self.write_partition(part, data)
        checksum = sha256_bytes(self.read(part.offset, written))
        LOG.info("restored %s from the golden copy (%s)", part.name, human_size(written))
        return {"partition": part.name, "bytes": written, "source": str(source),
                "sha256": checksum, "expected_sha256": sha256_bytes(data),
                "ok": checksum == sha256_bytes(data)}

    # -- serialisation -----------------------------------------------------------------
    def to_dict(self) -> Dict[str, Any]:
        decoded = self.registers_decoded()
        return {
            "image": str(self.path), "image_bytes": self.image_bytes,
            "image_size_human": human_size(self.image_bytes), "sector_size": self.sector_size,
            "sectors": self.sectors, "regions": list(REGIONS),
            "spec": self.spec.to_dict(), "registers": self.registers(),
            "cid": decoded["cid"], "csd": decoded["csd"], "ext_csd": decoded["ext_csd"],
            "health": self.health(), "life_estimate": regs.life_estimate(self.spec),
            "bad_blocks": [b.to_dict() for b in self.bad_blocks],
            "counters": self.counters.to_dict(), "signals": self.signals(),
            "notes": list(self.notes),
        }

    def save(self, path=None) -> Path:
        """Write `extcsd.json`: the registers and the health verdict, as Revive decoded them."""
        target = Path(path) if path else self.path.parent / "extcsd.json"
        payload = {
            "schema": "revive-lab-extcsd/1",
            "image": str(self.path), "spec": self.spec.to_dict(),
            "registers": self.registers(), **self.registers_decoded(),
            "life_estimate": regs.life_estimate(self.spec),
            "bad_blocks": [b.to_dict() for b in self.bad_blocks],
            "counters": self.counters.to_dict(), "signals": self.signals(),
            "notes": list(self.notes),
        }
        util.atomic_write(target, util.to_json(payload).encode("utf-8"))
        return target

    @classmethod
    def load(cls, path, spec_data: Optional[Dict[str, Any]] = None,
             sector_size: int = SECTOR, golden_dir=None) -> "VirtualEMMC":
        """Rebuild a controller around an existing image."""
        spec = RegisterSpec.from_dict(spec_data or {})
        emmc = cls(path, spec=spec, sector_size=sector_size, golden_dir=golden_dir)
        for block in emmc.spec.bad_blocks:
            emmc.bad_blocks.append(BadBlock.from_dict(block))
        return emmc

    # -- internals ---------------------------------------------------------------------
    def _require_image(self) -> None:
        if not self.path.exists():
            raise VirtualEmmcError(f"{self.path} does not exist - the device was deleted or "
                                   "never created")


def _mid_hex(name: str) -> str:
    for mid, label in emmc_mod.MANUFACTURERS.items():
        if label.lower() == (name or "").lower():
            return f"{mid:02X}"
    return "15"


# What the CLI, the API and the UI are allowed to change about a virtual chip, and how. The
# names are the ones a technician reaches for, so they match the datasheet fields.
SPEC_OPTIONS = {
    "manufacturer": "the chip maker (CID MID): samsung, hynix, micron, sandisk, toshiba, ...",
    "size": "nominal capacity, e.g. 64GB / 128G",
    "capacity": "nominal capacity in bytes",
    "health": "healthy | warning | dead - moves PRE_EOL_INFO and the life estimates",
    "pre_eol": "the PRE_EOL_INFO byte itself (0x01 / 0x02 / 0x03)",
    "firmware_version": "the eight ASCII bytes of EXT_CSD FIRMWARE_VERSION",
    "product_name": "the six-character CID product name",
    "serial": "the CID serial number",
    "write_cycles": "how many 4 MiB programme/erase cycles the chip has seen",
    "bad_blocks": "how many bad blocks to scatter across the user area",
}


def apply_options(emmc: "VirtualEMMC", options: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Change the chip's registers the way `--opt manufacturer=Micron` asks.

    One implementation behind the CLI, the web API and the UI, so the three cannot drift. An
    unknown name is an error rather than a silent no-op: a technician who types
    `manufaturer=Micron` needs to be told, not shown an unchanged chip.
    """
    applied: Dict[str, Any] = {}
    for raw, value in (options or {}).items():
        key = str(raw).strip().lower()
        if key not in SPEC_OPTIONS:
            raise VirtualEmmcError(
                f"unknown option {raw!r}; the chip settings are: "
                + ", ".join(sorted(SPEC_OPTIONS)))
        if key == "manufacturer":
            applied["manufacturer"] = emmc.set_manufacturer(value)["manufacturer"]
        elif key == "size":
            applied["size"] = human_size(emmc.set_size(value)["capacity_bytes"])
        elif key == "capacity":
            applied["capacity"] = human_size(emmc.set_capacity(int(value, 0))["capacity_bytes"])
        elif key == "health":
            applied["health"] = emmc.set_health(value)["health"]
        elif key == "pre_eol":
            applied["pre_eol"] = emmc.set_pre_eol(value)["pre_eol"]
        elif key == "firmware_version":
            applied["firmware_version"] = emmc.set_firmware_version(value)["firmware_version"]
        elif key == "product_name":
            applied["product_name"] = emmc.set_product_name(value)["product_name"]
        elif key == "serial":
            applied["serial"] = emmc.set_serial(value)["serial"]
        elif key == "write_cycles":
            applied["write_cycles"] = emmc.set_write_cycles(int(value, 0))["write_cycles"]
        elif key == "bad_blocks":
            blocks = emmc.add_random_bad_blocks(int(value, 0))
            applied["bad_blocks"] = len(blocks)
    return applied


def health_choices() -> Dict[str, str]:
    """The three health states and the PRE_EOL byte each one reports."""
    return {state: f"0x{regs.PRE_EOL_FOR_STATE[state]:02X}" for state in HEALTH_STATES}
